config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'currency_pairs#index'

  devise_for :users
  resources :currency_pairs
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, CurrencyPair, user_id: user.id
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_pair.rb
class CurrencyPair < ApplicationRecord
  enum target: %i[aud bgn brl cad chf cny czk dkk eur gbp hkd hrk huf idr ils inr
                  jpy krw mxn myr nok nzd php pln ron rub sek sgd thb try usd zar]

  belongs_to :user

  validates :amount, :target, :duration, presence: true
  validates :amount, :duration, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :currency_pairs
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/currency_pairs_controller.rb
class CurrencyPairsController < ApplicationController
  before_action :set_currency_pair, only: %i[show edit update destroy]
  load_and_authorize_resource

  def index
    @currency_pairs = CurrencyPair.where(user_id: current_user).order(:id)
  end

  def show
    @data = GetRatesService.new(@currency_pair).call
  end

  def new
    @currency_pair = CurrencyPair.new
  end

  def edit; end

  def create
    @currency_pair = CurrencyPair.new(currency_pair_params)

    if @currency_pair.save
      redirect_to @currency_pair, notice: 'Currency pair was successfully created.'
    else
      render :new
    end
  end

  def update
    if @currency_pair.update(currency_pair_params)
      redirect_to @currency_pair, notice: 'Currency pair was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @currency_pair.destroy
    redirect_to currency_pairs_url, notice: 'Currency pair was successfully destroyed.'
  end

  private

  def set_currency_pair
    @currency_pair = CurrencyPair.find(params[:id])
  end

  def currency_pair_params
    params.require(:currency_pair).permit(:amount, :target, :duration).merge(
      user: current_user
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/currency_pairs/_form.html.slim
.row
  .col-4
    = simple_form_for(@currency_pair) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      .form-group
        = f.input :amount, input_html: { min: '1' }
      .form-group
        = f.input :target, collection: CurrencyPair.targets.map { |key, value| [key.upcase, key] },
                  include_blank: false
      .form-group
        = f.input :duration, input_html: { min: '1' }
      .form-actions
        = f.button :submit, class: 'btn btn-outline-primary'
br

app/views/currency_pairs/edit.html.slim
h1
  | Editing Currency Pair
= render 'form', currency_pair: @currency_pair
= link_to 'Show', @currency_pair
|  | 
= link_to 'Back', currency_pairs_path

app/views/currency_pairs/index.html.slim
.row.pb-2
  .w-200.pl-3
    h3
      | Currency Pairs
  .col-9
    = link_to 'New Currency Pair', new_currency_pair_path, class: 'btn btn-outline-success btn-sm'
table.table
  thead
    tr
      th
        | Amount
      th
        | Target
      th
        | Duration
      th[colspan="3"]
  tbody
    - @currency_pairs.each do |currency_pair|
      tr
        td
          = currency_pair.amount
        td
          = currency_pair.target.upcase
        td
          = currency_pair.duration
        td
          = link_to 'Show rates', currency_pair, class: 'btn btn-outline-primary btn-sm mr-2'
          = link_to 'Edit', edit_currency_pair_path(currency_pair), class: 'btn btn-outline-dark btn-sm mr-2'
          = link_to 'Destroy', currency_pair, class: 'btn btn-outline-danger btn-sm mr-2',
                                              method: :delete, data: { confirm: 'Are you sure?' }

app/views/currency_pairs/new.html.slim
h1
  | New Currency Pair
= render 'form', currency_pair: @currency_pair
= link_to 'Back', currency_pairs_path

app/views/currency_pairs/show.html.slim
p
  strong
    | Amount: 
  = @currency_pair.amount
p
  strong
    | Target: 
  = @currency_pair.target.upcase
p
  strong
    | Duration: 
  = @currency_pair.duration

P 
  strong
    | Rate today: 
  = @data[:rate_today]

table.table
  thead
    tr
      th
        | Year
      th
        | Week
      th
        | Date
      th
        | Rate
      th
        | In total
      th
        | Profit/loss in comparison with today's rate
  tbody
    - @data[:for_table].each do |row|
      tr
        td= row[:year]
        td= row[:week_number]
        td= row[:date]
        td
          = row[:historical_rate]
          - if row[:highest]
            span.badge.badge-success.ml-1
              | highest
          - if row[:lowest]
            span.badge.badge-danger.ml-1
              | lowest
        td
          = humanized_money(row[:in_total])
          |  
          = @currency_pair.target.upcase
        td= row[:profit_loss]

= line_chart(@data[:for_chart], xtitle: 'Weeks', ytitle: 'Rate', min: @data[:lowest_value])      
      
= link_to 'Edit', edit_currency_pair_path(@currency_pair)
|  | 
= link_to 'Back', currency_pairs_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Exchanger
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link[rel="shortcut icon" href="favicon.ico" type="image/x-icon"]
  body
    .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-white.border-bottom.shadow-sm
      .container.d-flex
        = link_to root_path, class: 'navbar-brand d-flex align-items-center text-dark mr-md-auto'
          svg.bi.bi-bar-chart.mr-2[width="20" height="20" viewbox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg"]
            path[fill-rule="evenodd" d="M6 13H4v3h2v-3zm5-4H9v7h2V9zm5-5h-2v12h2V4zm-2-1a1 1 0 00-1 1v12a1 1 0 001 1h2a1 1 0 001-1V4a1 1 0 00-1-1h-2zM8 9a1 1 0 011-1h2a1 1 0 011 1v7a1 1 0 01-1 1H9a1 1 0 01-1-1V9zm-5 4a1 1 0 011-1h2a1 1 0 011 1v3a1 1 0 01-1 1H4a1 1 0 01-1-1v-3z" clip-rule="evenodd"]
          strong
            | Exchanger
        
        - if user_signed_in?
          ul.navbar-nav
            li.nav-item.dropdown
              a#dropdown-nav.nav-link.active.dropdown-toggle.text-dark aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#"= current_user.email
              .dropdown-menu aria-labelledby="dropdown-nav"
                - if user_signed_in?
                  = link_to 'My profile', edit_user_registration_path, class: 'dropdown-item'
                .dropdown-divider
                = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'
        - else
          = link_to 'Log in', new_user_session_path, class: 'nav-link active'
          = link_to 'Sign up', new_user_registration_path, class: 'nav-link active'
        
    .container.py-3
      - if notice
        p.alert.alert-success
          = notice
      - if alert
        p.alert.alert-danger
          = alert
        
      = yield
      
      footer.pt-4.my-md-5.pt-md-5.border-top
        .row
          .col-12.col-md
            small.d-block.mb-3.text-muted
              | © 2020